//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMemberView
    {
        public long RId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Committee_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<System.DateTime> Accessed_Date { get; set; }
        public Nullable<int> AccessedBy_Id { get; set; }
        public Nullable<bool> MemberCommiitteStatus { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> RoleStatus { get; set; }
        public string CommitteeName { get; set; }
        public Nullable<bool> CommitteeStatus { get; set; }
        public Nullable<int> CommitteMemberId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<int> UserCommitteId { get; set; }
        public Nullable<int> UserOrganizationId { get; set; }
    }
}
