//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Committee_Member = new HashSet<Committee_Member>();
            this.Task_Member = new HashSet<Task_Member>();
            this.Transactions = new HashSet<Transaction>();
            this.Users = new HashSet<User>();
            this.Member_Service = new HashSet<Member_Service>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public int Organization_Id { get; set; }
        public Nullable<int> Division_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public Nullable<int> Upazilas_Id { get; set; }
        public string Address { get; set; }
        public decimal PaymentFee { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Committee_Member> Committee_Member { get; set; }
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Upazila Upazila { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Member> Task_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Service> Member_Service { get; set; }
    }
}
