//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberServiceBill
    {
        public int Id { get; set; }
        public int MemberService_Id { get; set; }
        public decimal BillToPay { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public System.DateTime BillingDate { get; set; }
        public Nullable<System.DateTime> Received_Date { get; set; }
        public Nullable<int> ReceivedBy_Id { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Member_Service Member_Service { get; set; }
        public virtual User User { get; set; }
    }
}
