//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShipManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Member
    {
        public int Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<int> Task_Id { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Task Task { get; set; }
    }
}
